config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  resources :signups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'signups#index'
  # get 'login', to: 'signups#login'
  get 'dashboard', to: 'signups#dashboard'
  get 'all-signups', to: 'signups#all_signups'
  #match '/users/sign_up', :to => "devise/sessions#new", :via => [:get, :post]

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
end

app/models/signup.rb
class Signup < ApplicationRecord
  has_one_attached :selfie
  has_one_attached :photo_id
  validate :acceptable_image

  def acceptable_image
    return unless selfie.attached?

    unless selfie.byte_size <= 5.megabyte
      errors.add(:selfie, "is too big")
    end

    unless photo_id.byte_size <= 5.megabyte
      errors.add(:photo_id, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(selfie.content_type)
      errors.add(:selfie, "must be a JPEG or PNG")
    end

    unless acceptable_types.include?(photo_id.content_type)
      errors.add(:photo_id, "must be a JPEG or PNG")
    end
  end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  @token = ''
  @user_id = ''

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end


  def all_signups
    @signups = Signup.all
  end

  def login
  end

  def dashboard
    @u = params[:username]
    @p = params[:password]

    require 'uri'
    require 'net/http'
    require 'openssl'
    require 'json'

    org_id = params[:org]
    user_id = params[:user]
    cred_id = params[:cred]
    entry_id = params[:entry]

    url = URI("https://api.openpath.com/auth/login")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Post.new(url)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/json'
    request.body = "{\"email\":\"vladimir@recruiterswebsites.com\",\"password\":\"Placement123\"}"

   @response = http.request(request)
    puts @response.read_body

    body = JSON.parse(@response.read_body)
    @token = body['data']['token']

    require 'uri'
    require 'net/http'
    require 'openssl'

    url1 = URI("https://api.openpath.com/orgs/#{org_id}/users/#{user_id}/credentials/#{cred_id}/generateCloudKeyUnlockToken")

    http1 = Net::HTTP.new(url1.host, url1.port)
    http1.use_ssl = true
    http1.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request1 = Net::HTTP::Post.new(url1)
    request1["accept"] = 'application/json'
    request1["content-type"] = 'application/json'
    request1["authorization"] = @token
    request1.body = "{\"entryData\":[{\"entryId\":#{entry_id}}]}"

    response1 = http1.request(request1)
    body1 = JSON.parse(response1.read_body)
    cloud_key = body1['data']['cloudKeyUnlockToken']

    require 'uri'
    require 'net/http'
    require 'openssl'

    url2 = URI("https://api.openpath.com/tokens/cloudKeyUnlockTokens/#{cloud_key}/use")

    http2 = Net::HTTP.new(url2.host, url2.port)
    http2.use_ssl = true
    http2.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request2 = Net::HTTP::Post.new(url2)
    request2["content-type"] = 'application/json'

    @response2 = http2.request(request2)







  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    code = rand(10000...99999)


    @signup.update_attributes(:code => code)
    @signup.save

    require 'twilio-ruby'



    # Your Account Sid and Auth Token from twilio.com/console
    # DANGER! This is insecure. See http://twil.io/secure
    account_sid = ENV['TWILIO_SID']
    auth_token = ENV['TWILIO_TOKEN']
    client = Twilio::REST::Client.new(account_sid, auth_token)

    message = client.messages
                  .create(
                      body: "Welcome to Snoozze Mattress after hours access. Your verification code is #{code}. \n Once verified use the unlock door button to start shopping.",
                      from: '+16266189226',
                      to: "+1#{@signup.phone}"
                  )


# Login as SuperAdmin
#     require 'uri'
#     require 'net/http'
#     require 'openssl'
#     require 'json'
#
#     url = URI("https://api.openpath.com/auth/login")
#
#     http = Net::HTTP.new(url.host, url.port)
#     http.use_ssl = true
#     http.verify_mode = OpenSSL::SSL::VERIFY_NONE
#
#     request = Net::HTTP::Post.new(url)
#     request["accept"] = 'application/json'
#     request["content-type"] = 'application/json'
#     request.body = "{\"email\":\"jeff@recruiterswebsites.com\",\"password\":\"Placement123\"}"
#
#     @response = http.request(request)
#     puts @response.read_body
#
#     body = JSON.parse(@response.read_body)
#     @token = body['data']['token']

# Rails local signup
    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render :show, status: :created, location: @signup }
      else
        format.html { render :new }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
# Create User
#     require 'uri'
#     require 'net/http'
#     require 'openssl'
#
#     url = URI("https://api.openpath.com/orgs/3240/users")
#
#     http = Net::HTTP.new(url.host, url.port)
#     http.use_ssl = true
#     http.verify_mode = OpenSSL::SSL::VERIFY_NONE
#
#     request = Net::HTTP::Post.new(url)
#     request["accept"] = 'application/json'
#     request["content-type"] = 'application/json'
#     request["authorization"] = @token
#     email = @signup.email
#     first_name = @signup.first_name
#     last_name = @signup.last_name
#     # password = @signup.password
#     request.body = "{\"identity\":{\"email\":\"#{email}\",\"firstName\":\"#{first_name}\",\"lastName\":\"#{last_name}\"}}"
#     # ,\"password\":\"#{password}\"
#     @response = http.request(request)
#     # puts @response.read_body
#     body = JSON.parse(@response.read_body)
#     @user_id = body['data']['id']
# # Adds user to group
#     require 'uri'
#     require 'net/http'
#     require 'openssl'
#
#     url1 = URI("https://api.openpath.com/orgs/3240/groups/11796/users/#{@user_id}")
#
#     http1 = Net::HTTP.new(url1.host, url1.port)
#     http1.use_ssl = true
#     http1.verify_mode = OpenSSL::SSL::VERIFY_NONE
#
#     request1 = Net::HTTP::Put.new(url1)
#     request1["authorization"] = @token
#
#     response1 = http1.request(request1)
#     puts response1.read_body
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Mobile Phone Verified.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def signup_params
      params.require(:signup).permit(:first_name, :last_name, :verified, :email, :address, :address2, :city, :state, :zip, :phone, :photo_id, :selfie, :user_id, :location_id).merge(user_id: current_user.id)
    end
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/_form.html.erb
<%= form_with(model: signup, local: true) do |form| %>
  <% if signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :photo_id %>
    <%= form.text_field :photo_id %>
  </div>

  <div class="field">
    <%= form.label :selfie %>
    <%= form.text_field :selfie %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/signups/dashboard.html.erb
<div id="result">
<% if @response2.code == '204' %>
  <%= 'Success' %>
 <% else %>
  <% 'Error' %>
  <% end %>

</div>

app/views/signups/edit.html.erb
<h1>Editing Signup</h1>

<%= render 'form', signup: @signup %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin != 'yes' %>
  <script type="text/javascript">
      window.location.href="/signups/new"
  </script>
<% end %>
<h1>Signups</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Photo</th>
      <th>Selfie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @signups.each do |signup| %>
    <% created_ago = (Time.now - signup.created_at) / 1.hours %>

    <% #if created_ago.round > 24 %>
     <% #next %>
  <% #end %>
      <tr>
        <td><%= signup.first_name %></td>
        <td><%= signup.last_name %></td>
        <td><%= signup.email %></td>
        <td><%= signup.address %></td>
        <td><%= signup.address2 %></td>
        <td><%= signup.city %></td>
        <td><%= signup.state %></td>
        <td><%= signup.zip %></td>
        <td><%= signup.phone %></td>
        <td><%= image_tag(signup.photo_id, style: 'width:100px') if signup.selfie.attached? %></td>
        <td><%= image_tag(signup.selfie, style: 'width:100px') if signup.photo_id.attached? %></td>
        <td><%= link_to 'Show', signup %></td>
        <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
        <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signup', new_signup_path %>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>

app/views/signups/login.html.erb
<div class="container loginbg">
  <br>
  <div class="d-flex justify-content-center h-100">
    <div class="card">
      <div class="card-header">
        <h3>Sign In</h3>
        <div class="d-flex justify-content-end social_icon">
        </div>
      </div>
      <div class="card-body">
        <form action="/dashboard" method="post">
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
          <div class="input-group form-group">
            <input id="username" name="username" type="text" class="form-control" placeholder="username">
          </div>
          <div class="input-group form-group">
            <input name="password" id="password" type="password" class="form-control" placeholder="password">
          </div>

          <div class="form-group">
            <input type="submit" value="Login" class="btn float-right login_btn">
          </div>
        </form>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-center links">
          Don't have an account?<a href="#">Sign Up</a>
        </div>
        <div class="d-flex justify-content-center">
          <a href="#">Forgot your password?</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/signups/new.html.erb
<!--<div class="container">-->
<h1>New Signup</h1>

<%#= render 'form', signup: @signup %>

  <%#= form_for @signup do |f| %>
    <%#= f.label :first_name %>
    <%#= f.text_field :first_name %>

    <%#= f.label :last_name %>
    <%#= f.text_field :last_name %>

    <%#= f.label :email %>
    <%#= f.text_field :email %>

    <%#= f.label :address %>
    <%#= f.text_field :address %>

    <%#= f.label :address2 %>
    <%#= f.text_field :address2 %>

    <%#= f.label :city %>
    <%#= f.text_field :city %>

    <%#= f.label :state %>
    <%#= f.text_field :state %>

    <%#= f.label :zip %>
    <%#= f.text_field :zip %>

    <%#= f.label :phone %>
    <%#= f.text_field :phone %>
<!--    <br>-->
    <%#= f.collection_select(:location_id, Location.all, :id, :name) %>

<!--    <br>-->

    <%#= f.label :selfie %>
    <%#= f.file_field :selfie %>
<!--    <br>-->
<!--    <br>-->
    <%#= f.label :photo_id %>
    <%#= f.file_field :photo_id %>
<!--    <br>-->
<!--    <br>-->

    <%#= f.submit  %>
  <%# end %>


<%#= link_to 'Back', signups_path %>
<!--</div>-->









<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://kit.fontawesome.com/fe8b25c4e5.js" crossorigin="anonymous"></script>



<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Snoozze Mattress Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>


  <div class="container bootstrap snippet">
    <div class="row">

      <div class="col-sm-12">



            <%= form_for @signup do |form| %>
          <div class="form-group">

            <div class="col-xs-6">
              <label for="first_name"><h4>First Name</h4></label>
              <%= form.text_field :first_name, required: true %>

            </div>
          </div>
          <div class="form-group">

            <div class="col-xs-6">
              <label for="last_name"><h4>Last Name</h4></label>
              <%= form.text_field :last_name, required: true %>

            </div>
          </div>


              <div class="form-group">

                <div class="col-xs-6">
                  <label for="first_name"><h4>Email</h4></label>
                  <%= form.text_field :email, required: true %>

                </div>
              </div>
          <div class="form-group">

            <div class="col-xs-6">
              <label for="password"><h4>Mobile Phone</h4></label>
              <%= form.text_field :phone, required: true %>

            </div>
          </div>
              <div class="form-group">

                <div class="col-xs-6">
                  <label for="last_name"><h4>Address</h4></label>
                  <%= form.text_field :address, required: true %>

                </div>
              </div>

              <div class="form-group">

                <div class="col-xs-6">
                  <label for="phone"><h4>Address 2</h4></label>
                  <%= form.text_field :address2 %>

                </div>
              </div>

              <div class="form-group">
                <div class="col-xs-6">
                  <label for="mobile"><h4>City</h4></label>
                  <%= form.text_field :city, required: true %>

                </div>
              </div>
              <div class="form-group">

                <div class="col-xs-6">
                  <label for="email"><h4>State</h4></label>
                  <%= form.text_field :state, required: true %>

                </div>
              </div>
              <div class="form-group">

                <div class="col-xs-6">
                  <label for="email"><h4>Zip</h4></label>
                  <%= form.text_field :zip, required: true %>

                </div>
              </div>


              <div class="form-group">

                <div class="col-xs-6">
                  <label for="password"><h4>Store Location</h4></label>
                  <%= form.collection_select(:location_id, Location.all, :id, :name) %>
                  <p style="visibility: hidden">test</p>
                </div>
              </div>

          <div class="form-group">

            <div class="col-xs-6">
              <label for="selfie"><h4>Selfie</h4></label>
              <%= form.file_field :selfie, required: true %>

            </div>
          </div>

          <div class="form-group">

            <div class="col-xs-6">
              <label for="license"><h4>Drivers License</h4></label>
              <%= form.file_field :photo_id, required: true %>

            </div>
          </div>

          <div class="col-xs-6">
            <h4 style="visibility: hidden"></h4>
          <div id="form-submit"  class="actions">
            <%= form.submit %>
          </div>

          </div>
          </div>




            <% end %>


            <hr>

          </div><!--/tab-pane-->



    </div><!--/col-9-->
  </div><!--/row-->
<%#end %>



<style>

  #signup_location_id{
    width: 83%;
  }

</style>

app/views/signups/show.html.erb
<!-- Modal -->
<div class="modal show fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Mobile Phone Verification</h5>
      </div>
      <div class="modal-body">
        <h6>We have sent a confirmation code to <%= @signup.phone %>.</h6>
        Enter Code:
        <input id="verify">
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


<div class="container">

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="background: #337ab7a3;">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"> <i id="success-icon" style="color: lightgreen; display: none" class="fas fa-lock-open-alt fa-2x"> <span id="success-text">The Store is now unlocked.</span></i>
            <div style="display: none" id="failure">
              <i style="color: red" class="fas fa-exclamation-triangle fa-2x"></i>
              Something went wrong
            </div><span id="loading-text">Processing ... </span></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Avoid the pushy salespeople with the option to try before you buy at one of our local 🏪 . Order and pick up your mattress in the *same day. No waiting. No hassle. Just comfort. 😴
        </div>
        <div class="modal-footer">
          <!--        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
          <button id="close" type="button" data-dismiss="modal" class="btn btn-primary">Close</button>
        </div>
      </div>
    </div>
  </div>
<p id="notice"><%= notice %></p>

</div>
<%= @body %>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://kit.fontawesome.com/fe8b25c4e5.js" crossorigin="anonymous"></script>



<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Snoozze Mattress Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<% created_ago = (Time.now - @signup.created_at) / 1.hours %>

<% if created_ago.round > 24 %>
  <%= "Session Expired " %>
  <%= link_to 'New Session', new_signup_path %>
  <% else %>


<div class="container bootstrap snippet">
  <center>
  <h2> Welcome to <%= Location.find(@signup.location_id).name %> Snoozze Mattress Store </h2>
  <p>Use the unlock button on the right to unlock the front door. Your session will expire in <%=  24 - created_ago.round  %> hours. After that you will need to re-register.</p>
  </center>
  <hr>
  <div class="row" style="margin-left: 10px">
    <div class="col-xs-7"><h1><%= @signup.first_name %> <%= @signup.last_name %></h1></div>

    <div class="col-xs-5">
      <button data-toggle="modal" disabled="disabled" data-target="#exampleModal" class=" unlock btn pull-right" style="margin: 20px;" id="unlock_button">Unlock Front Door</button>
    </div>
    <%#= "There are  #{24 - created_ago.round} hours left in your session" %>
  </div>
  <div class="row">
    <div class="col-sm-3"><!--left col-->


      <div id="profile-img" class="text-center">
        <%= image_tag(@signup.selfie) if @signup.selfie.attached? %>

      </div></hr><br>


      <div class="panel panel-default">
        <div class="panel-heading">Drivers License</div>
        <%= image_tag(@signup.photo_id) if @signup.photo_id.attached? %>

      </div>



    </div><!--/col-3-->
    <div class="col-sm-9">


      <div class="tab-content">
        <div class="tab-pane active" id="home">
          <%= form_for @signup, :html => {:id => "signup_form"} do |form| %>
            <div class="form-group">

              <div class="col-xs-6">
                <label for="first_name"><h4>Email</h4></label>
                <%= form.text_field :email, :disabled => true %>

              </div>
            </div>
            <div class="form-group">

              <div class="col-xs-6">
                <label for="last_name"><h4>Address</h4></label>
                <%= form.text_field :address, :disabled => true %>

              </div>
            </div>

            <div class="form-group">

              <div class="col-xs-6">
                <label for="phone"><h4>Address 2</h4></label>
                <%= form.text_field :address2, :disabled => true %>

              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-6">
                <label for="mobile"><h4>City</h4></label>
                <%= form.text_field :city, :disabled => true %>

              </div>
            </div>
            <div class="form-group">

              <div class="col-xs-6">
                <label for="email"><h4>State</h4></label>
                <%= form.text_field :state, :disabled => true %>

              </div>
            </div>
            <div class="form-group">

              <div class="col-xs-6">
                <label for="email"><h4>Zip</h4></label>
                <%= form.text_field :zip, :disabled => true %>

              </div>
            </div>
            <div class="form-group">

              <div class="col-xs-6">
                <label for="password"><h4>Mobile Phone</h4></label>
                <%= form.text_field :phone, :disabled => true %>

              </div>
            </div>

            <div class="form-group">

              <div class="col-xs-6">
                <label for="password"><h4> Store Location</h4></label>
                <div class="location_dropdown">
                <%= form.collection_select(:location_id, Location.all, :id, :name) %>
                </div>
              </div>
            </div>

            <div class="form-group">

              <div class="col-xs-6">
                <%= form.hidden_field :verified, value:"1"   %>
              </div>
            </div>


            <br>

              <%= form.submit "Update Location", class: 'btn btn-success' %>

          <% end %>


          <hr>

        </div><!--/tab-pane-->

      </div><!--/tab-pane-->
    </div><!--/tab-content-->

  </div><!--/col-9-->
</div><!--/row-->
  <%end %>




<script>
    $( "#close" ).click(function() {
        $("#profile-img").click()
    });


    $( "#unlock_button" ).click(function() {
    $.ajax({
            url: "<%= request.base_url %>/dashboard?code=<%= @signup.code %>&org=<%= Location.find(@signup.location_id).org_id %>&user=<%= Location.find(@signup.location_id).user_id %>&cred=<%= Location.find(@signup.location_id).cred_id %>&entry=<%= Location.find(@signup.location_id).entry_id %>",
            type: 'GET',
            success: function(res) {
                var result = $("#result", res)[0].textContent
                console.log(result);
                if (result.indexOf('Success') >= 0){
                    $('#success-icon').show();
                    $('#loading-text').hide();
                    // $('#success-icon').delay(1000).fadeOut(2000)
                }
                else{
                    $('#failure').show();
                    // $('#failure').delay(1000).fadeOut(2000)
                }
            }
        });
    });

    $("#verify").on("input", function() {
      if (jQuery('#verify').val() == <%= @signup.code %>){
          $("#signup_form").submit();

      }
    });

    <% if @signup.verified == '1' %>
    $( document ).ready(function() {
        $('#exampleModalCenter').removeClass('show');
        document.getElementById("unlock_button").disabled = false;
    });
      <% end %>



</script>

<style>
  .btn-success{
    margin-top: 10px;
  }

  .location_dropdown {
    position: relative;
  }



  .location_dropdown:after {
    content: "";
    position: absolute;
    right: 10px;
    top: 11px;
    width: 0;
    height: 0;
    border-left: 10px solid transparent;
    border-right: 10px solid transparent;
    border-top: 10px solid #333;
  }

</style>